version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uroot", "-p${DB_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build: ./
    env_file:
      - ./.env
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${DB_DRIVER}
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
volumes:
  mysql_data:
networks:
  default:
    external: true
    name: shared-net
